'use client';
import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';
import CodeBlock from './CodeBlock';
import {
  Globe,
  ScanEye,
  ImageIcon,
  FileText,
  ExternalLink,
  Copy,
  Volume2,
  RefreshCw,
  ThumbsUp,
  ThumbsDown,
  Check,
} from 'lucide-react';
import type { Message as Msg } from './types';

const MODE_LABEL: Record<string, { icon: any; text: string; cls: string; live?: boolean }> = {
  search: { icon: Globe, text: 'Searched the web', cls: 'search', live: true },
  vision: { icon: ScanEye, text: 'Analyzing upload', cls: 'vision' },
  image: { icon: ImageIcon, text: 'Generated image', cls: 'image' },
};

interface MessageProps {
  msg: Msg;
  onRegenerate?: () => void;
  onRun?: (code: string, language: string) => void;
}

export default function Message({ msg, onRegenerate, onRun }: MessageProps) {
  const isUser = msg.role === 'user';
  const badge = msg.mode && MODE_LABEL[msg.mode] ? MODE_LABEL[msg.mode] : null;
  const [copied, setCopied] = useState(false);
  const [feedback, setFeedback] = useState<'like' | 'dislike' | null>(null);
  const [speaking, setSpeaking] = useState(false);

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(msg.content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // ignore
    }
  }

  function handleReadAloud() {
    if (!window.speechSynthesis) return;
    if (window.speechSynthesis.speaking) {
      window.speechSynthesis.cancel();
      setSpeaking(false);
      return;
    }
    const utter = new SpeechSynthesisUtterance(msg.content);
    utter.onend = () => setSpeaking(false);
    utter.onerror = () => setSpeaking(false);
    setSpeaking(true);
    window.speechSynthesis.speak(utter);
  }

  const showActions = !isUser && !msg.streaming && msg.content;

  return (
    <div className={`msg ${isUser ? 'user' : 'assistant'}`}>
      <div className="msg-head">
        <span className="msg-author">
          {isUser ? 'You' : <>Prome<span className="who">theus</span></>}
        </span>
        {badge && (
          <span className={`mode-badge ${badge.cls} ${badge.live ? 'live' : ''}`}>
            <span className="dot" />
            <badge.icon size={12} /> {badge.text}
          </span>
        )}
      </div>

      <div className="msg-body">
        {/* User attachments */}
        {isUser && msg.attachments && msg.attachments.length > 0 && (
          <div className="attach-row">
            {msg.attachments.map((a) =>
              a.mime.startsWith('image/') ? (
                <span className="attach-chip" key={a.id}>
                  <img src={`/api/files/${a.id}`} alt={a.name} />
                  {a.name}
                </span>
              ) : (
                <span className="attach-chip" key={a.id}>
                  <FileText size={16} color="var(--gold)" /> {a.name}
                </span>
              )
            )}
          </div>
        )}

        {/* Generated image */}
        {msg.imageUrl && (
          <div className="gen-image">
            <img src={msg.imageUrl} alt="Generated by Prometheus" />
          </div>
        )}

        {/* Text */}
        {msg.content && (
          <div className="md">
            <ReactMarkdown
              remarkPlugins={[remarkGfm, remarkMath]}
              rehypePlugins={[rehypeKatex]}
              components={{ pre: (p: any) => <CodeBlock {...p} onRun={onRun} /> }}
            >
              {msg.content}
            </ReactMarkdown>
          </div>
        )}

        {showActions && (
          <div className="msg-actions">
            <button
              className="msg-action-btn"
              title="Copy"
              onClick={handleCopy}
              aria-label="Copy response"
            >
              {copied ? <Check size={14} /> : <Copy size={14} />}
            </button>
            <button
              className={`msg-action-btn ${speaking ? 'active' : ''}`}
              title={speaking ? 'Stop reading' : 'Read aloud'}
              onClick={handleReadAloud}
              aria-label="Read aloud"
            >
              <Volume2 size={14} />
            </button>
            {onRegenerate && (
              <button
                className="msg-action-btn"
                title="Re-generate"
                onClick={onRegenerate}
                aria-label="Re-generate response"
              >
                <RefreshCw size={14} />
              </button>
            )}
            <button
              className={`msg-action-btn ${feedback === 'like' ? 'active' : ''}`}
              title="Helpful"
              onClick={() => setFeedback((f) => (f === 'like' ? null : 'like'))}
              aria-label="Like response"
            >
              <ThumbsUp size={14} />
            </button>
            <button
              className={`msg-action-btn ${feedback === 'dislike' ? 'active' : ''}`}
              title="Not helpful"
              onClick={() => setFeedback((f) => (f === 'dislike' ? null : 'dislike'))}
              aria-label="Dislike response"
            >
              <ThumbsDown size={14} />
            </button>
          </div>
        )}

        {msg.streaming && <span className="typing-cursor">&nbsp;</span>}

        {/* Sources */}
        {msg.sources && msg.sources.length > 0 && (
          <div className="sources">
            <p className="label">Sources</p>
            {msg.sources.map((s, i) => (
              <div className="source-item" key={i}>
                <span className="num">{i + 1}</span>
                <a href={s.url} target="_blank" rel="noopener noreferrer">
                  <div className="src-title">{s.title}</div>
                  <div className="src-url">
                    {s.url} <ExternalLink size={10} style={{ display: 'inline' }} />
                  </div>
                </a>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
